language: rust
branches:
  only:
    master
rust:
  - nightly
  - stable
before_script: rustup component add rustfmt clippy
script:
  - cargo test --all
  - cargo clippy --all --all-targets --all-features -- -D warnings
  - cargo fmt --all -- --check
