language: rust
branches:
  only:
    master

matrix:
  include:
    - rust: nightly
      env:
        RUST_TEST_THREADS: 1
      script: cargo test --all
    - rust: stable
      env:
        RUST_TEST_THREADS: 1
      script: cargo test --all
    - rust: beta
      env:
        RUST_TEST_THREADS: 1
      script: cargo test --all
    - env: 
        CLIPPY: enabled
      rust: nightly
      script: cargo build --features "dev"
    - env:
        RUSTFMT: enabled
      rust: nightly
      before_script:
        - (cargo install rustfmt-nightly --force || true)
        - export PATH=$PATH:$HOME/.cargo/bin
      script: cargo fmt -- --write-mode=diff
