[package]
name = "chef_api"
version = "0.1.0"
authors = ["Thom May <thom@chef.io>"]

[dependencies]
time = "*"
log = "*"
rustc-serialize = "*"
clippy = {version = "*", optional = true}
hyper = {version = "0.9", default_features = false, features = [ "serde-serialization" ] }
hyper-openssl = "0.1"

url = "*"
chrono = "*"
openssl = "0.9"
env_logger = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
error-chain = "0.7"

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "chef_api"
doc = false
test = false
