[package]
name = "chef_api"
version = "0.1.0"
authors = ["Thom May <thom@chef.io>"]

[dependencies]
time = "0.1"
log = "0.3"
rustc-serialize = "0.3"
clippy = {version = "0.0.21", optional = true}
hyper = {version = "0.7", features = [ "serde-serialization" ] }
url = "*"
chrono = "0.2"
openssl = "0.7"
env_logger = "0.3"
serde = "*"
serde_macros = "*"
serde_json = "*"

[features]
default = []
dev = ["clippy"]
