[package]
name = "chef_api"
version = "0.1.0"
authors = ["Thom May <thom@chef.io>"]

[dependencies]
time = "*"
log = "*"
rustc-serialize = "*"
clippy = {version = "*", optional = true}
hyper = {version = "0.9", features = [ "serde-serialization" ] }
url = "*"
chrono = "*"
openssl = "*"
env_logger = "0.3"
serde = "*"
serde_macros = "*"
serde_json = "*"
error-chain = "0.4.0"

[features]
default = []
dev = ["clippy"]

[[bin]]
name = "chef_api"
doc = false
test = false
